version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/spring
hooks:
  BeforeInstall:
    - location: ./start.sh
      runas: root
  AfterInstall:
    - location: ./stop.sh
      runas: root

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:region:account_id:task-definition/task_defn:revision"
        LoadBalancerInfo:
          ContainerName: "container_name"
          ContainerPort: 8080
