version: 0.0
os: linux
files:
  - source: /src/main/java/com/java/docker/test/App.java
hooks:
  BeforeInstall:
    - location: /stop.sh
      runas: ec2-user
  AfterInstall:
    - location: /start.sh
      runas: ec2-user
